/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.CartDAO;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.text.MaskFormatter;

import model.CartItem;
import model.ProductModel;
import util.SessionManager;



/**
 *
 * @author Lenovo
 */
public class CartView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CartView.class.getName());
    private final CartDAO cartDAO;
    
    /**
     * Creates new form Dashboard
     */
public CartView(CartDAO cartDAO) {
        this.cartDAO = cartDAO;
    int userId = SessionManager.getCurrentUserId();



    initComponents();
    Pop.add(Account);
    Pop.add(Order);
    Pop.add(OUT);

    loadCartItems();
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pop = new javax.swing.JPopupMenu();
        Account = new javax.swing.JMenuItem();
        Order = new javax.swing.JMenuItem();
        OUT = new javax.swing.JMenuItem();
        Header = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subname = new javax.swing.JLabel();
        Profile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productcontainer = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        aboutus = new javax.swing.JLabel();
        aboutus1 = new javax.swing.JLabel();
        aboutus2 = new javax.swing.JLabel();
        aboutus3 = new javax.swing.JLabel();
        Help = new javax.swing.JButton();
        Contact = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        Buy = new javax.swing.JButton();
        Address = new javax.swing.JTextField();
        Phone = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();

        Pop.setBorder(null);
        Pop.setBorderPainted(false);
        Pop.setPreferredSize(new java.awt.Dimension(125, 125));

        Account.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account (2).png"))); // NOI18N
        Account.setText("My Account");
        Account.setBorder(null);
        Account.setBorderPainted(false);
        Account.addActionListener(this::AccountActionPerformed);
        Pop.add(Account);

        Order.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bag (2).png"))); // NOI18N
        Order.setText("Order Status");
        Order.setBorder(null);
        Order.setBorderPainted(false);
        Pop.add(Order);

        OUT.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        OUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit (2).png"))); // NOI18N
        OUT.setText("Log Out");
        OUT.setBorder(null);
        OUT.setBorderPainted(false);
        Pop.add(OUT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 0, 0));

        name.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 30)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("GRAVE RUN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newlogo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        subname.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        subname.setForeground(new java.awt.Color(255, 255, 255));
        subname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subname.setText("RUN BEYOND THE GRAVE");

        Profile.setBackground(new java.awt.Color(0, 0, 0));
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_a.png"))); // NOI18N
        Profile.setBorder(null);
        Profile.setBorderPainted(false);
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Profile.setFocusPainted(false);
        Profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Profile.addActionListener(this::ProfileActionPerformed);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(subname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 995, Short.MAX_VALUE)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Productcontainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(Productcontainer);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(0, 0, 0));

        aboutus.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setText("About Us");

        aboutus1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus1.setForeground(new java.awt.Color(255, 255, 255));
        aboutus1.setText("Where style meets comfort in every step.");

        aboutus2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus2.setForeground(new java.awt.Color(255, 255, 255));
        aboutus2.setText("Your go-to destination for everyday sneakers.");

        aboutus3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus3.setForeground(new java.awt.Color(255, 255, 255));
        aboutus3.setText("An online shoe store that makes browsing and buying footwear easy.");

        Help.setBackground(new java.awt.Color(0, 0, 0));
        Help.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        Help.setForeground(new java.awt.Color(255, 255, 255));
        Help.setText("Help");
        Help.setBorder(null);
        Help.setBorderPainted(false);
        Help.setFocusPainted(false);
        Help.addActionListener(this::HelpActionPerformed);

        Contact.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("Contact");

        mail.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("graverun16@gmail.com");

        phone.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("9808404997");

        location.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setText("Kathmandu, Nepal");

        Buy.setBackground(new java.awt.Color(0, 0, 0));
        Buy.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Buy.setForeground(new java.awt.Color(255, 255, 255));
        Buy.setText("Buy All");
        Buy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 9, true));
        Buy.setFocusPainted(false);
        Buy.setMaximumSize(new java.awt.Dimension(350, 65));
        Buy.setMinimumSize(new java.awt.Dimension(350, 65));
        Buy.setPreferredSize(new java.awt.Dimension(350, 65));
        Buy.addActionListener(this::BuyActionPerformed);

        Address.setBackground(new java.awt.Color(73, 17, 17));
        Address.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setText("Enter your Address");
        Address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        Address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AddressFocusLost(evt);
            }
        });

        Phone.setBackground(new java.awt.Color(73, 17, 17));
        Phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        Phone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            Phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########## ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Phone.setText("Enter your Phone Number");
        Phone.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter your Phone Number:");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        Total.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aboutus)
                            .addComponent(aboutus1)
                            .addComponent(aboutus2)
                            .addComponent(aboutus3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                                .addComponent(Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mail)
                                        .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(location, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(Contact, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(footerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                        .addComponent(aboutus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutus2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutus3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                        .addComponent(Contact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location)
                        .addGap(3, 3, 3))
                    .addComponent(Help, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
                                    
 Dashboard1 dashboard = new Dashboard1();
        dashboard.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel2MouseClicked

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed

    }//GEN-LAST:event_ProfileActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
            HelpPage help=new HelpPage();
        help.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountActionPerformed

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
// 1️⃣ Validate address & phone
String address = Address.getText().trim();
String phone = Phone.getText().replaceAll("\\s", "").trim();

if (address.isEmpty() || address.equals("Enter your Address") || phone.length() < 10) {
    JOptionPane.showMessageDialog(
        this,
        "Please enter a valid address and phone number",
        "Missing Info",
        JOptionPane.WARNING_MESSAGE
    );
    return;
}

// 2️⃣ Get cart items
List<CartItem> cartItems = cartDAO.getAllItems();
if (cartItems.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Your cart is empty!");
    return;
}

try {
    // 3️⃣ Redirect to Stripe Checkout
    String url = util.StripeService.checkoutCart(cartItems);
    java.awt.Desktop.getDesktop().browse(new java.net.URI(url));

    // 4️⃣ Save all items as an order in DB
    int userId = util.SessionManager.getCurrentUser().getUserId();
    dao.OrderDAO orderDAO = new dao.OrderDAO(userId);
    int orderId = orderDAO.createOrder(cartItems, address, "Stripe", "StripePayment");

    // 5️⃣ Show success message
    if (orderId > 0) {
        JOptionPane.showMessageDialog(
            this,
            "✅ Thank you for choosing us! All items purchased successfully. Order ID: " + orderId,
            "Order Confirmed",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
            this,
            "❌ Order failed to save in database.",
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }

    // 6️⃣ Optionally clear cart UI
    cartDAO.clearCart();
   // your method to refresh cart view

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(
        this,
        "Payment failed: " + e.getMessage(),
        "Stripe Error",
        JOptionPane.ERROR_MESSAGE
    );
}

   // TODO add your handling code here:
    }//GEN-LAST:event_BuyActionPerformed

    private void AddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddressFocusGained
        if (Address.getText().equals("Enter your Address")) {
            Address.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFocusGained

    private void AddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddressFocusLost
        if (Address.getText().trim().isEmpty()) {
            Address.setText("Enter your Address");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFocusLost

    private void PhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneFocusGained
        Phone.setForeground(java.awt.Color.WHITE);
        Phone.setCaretPosition(0);// TODO add your handling code here:
    }//GEN-LAST:event_PhoneFocusGained

    private void PhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneFocusLost

        String phone = Phone.getText().replaceAll("\\s", "");

        if (phone.length() < 10) {
            JOptionPane.showMessageDialog(
                this,
                "Phone number must be 10 digits",
                "Invalid Phone",
                JOptionPane.WARNING_MESSAGE
            );
            Phone.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFocusLost



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Account;
    private javax.swing.JTextField Address;
    private javax.swing.JButton Buy;
    private javax.swing.JLabel Contact;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Help;
    private javax.swing.JMenuItem OUT;
    private javax.swing.JMenuItem Order;
    private javax.swing.JFormattedTextField Phone;
    private javax.swing.JPopupMenu Pop;
    private javax.swing.JPanel Productcontainer;
    private javax.swing.JButton Profile;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel aboutus;
    private javax.swing.JLabel aboutus1;
    private javax.swing.JLabel aboutus2;
    private javax.swing.JLabel aboutus3;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel location;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel subname;
    // End of variables declaration//GEN-END:variables







public javax.swing.JButton getProfileButton() {
    return Profile;
}

public javax.swing.JPopupMenu getPopupMenu() {
    return Pop;
}

public javax.swing.JPanel getProductContainer() {
    return Productcontainer;
}

// Footer Help Button
public javax.swing.JButton getHelpButton() {
    return Help;
}
private void loadCartItems() {
    Productcontainer.removeAll(); 

    for (CartItem item : cartDAO.getAllItems()) {
        ProductCartPanel panel = new ProductCartPanel();
        panel.setProductId(item.getProduct().getProductId());
        panel.setProductName(item.getProduct().getName());
        panel.setUnitPrice(item.getProduct().getPrice());
        panel.setQuantity(item.getQuantity());
        panel.setProductImage(item.getProduct().getImageUrl());

        // Quantity change listener
        panel.addQuantityListeners(() -> {
            cartDAO.updateQuantity(item.getProduct(), panel.getQuantity());
            updateTotal();
        });

        // Delete listener
        panel.addDeleteListener(() -> {
            cartDAO.removeProduct(item.getProduct().getProductId());
            Productcontainer.remove(panel);
            Productcontainer.revalidate();
            Productcontainer.repaint();
            updateTotal();
        });

        Productcontainer.add(panel);
    }

    Productcontainer.revalidate();
    Productcontainer.repaint();

    // Set total initially
    updateTotal();
}
private BigDecimal calculateTotal() {
    BigDecimal total = BigDecimal.ZERO;
    for (CartItem item : cartDAO.getAllItems()) {
        total = total.add(item.getProduct().getPrice()
                        .multiply(BigDecimal.valueOf(item.getQuantity())));
    }
    return total.setScale(2, BigDecimal.ROUND_HALF_UP);
}

private void updateTotal() {
    Total.setText("Total: Rs " + calculateTotal().toPlainString());
}





}



  



