package view;

import controller.DashboardController;
import model.AdminProductModel;
import util.SessionManager;
import java.awt.BorderLayout;
import javax.swing.*;

/**
 * DASHBOARD VIEW - Pure UI Layer
 * Contains ZERO business logic - only UI rendering
 */
public class Dashboard1 extends javax.swing.JFrame {

    private DashboardController controller;
    private static final String SEARCH_PLACEHOLDER = "Search by brands";
    private JPanel productGridPanel; // ✅ Holds all product cards
    
    public Dashboard1() {
        initComponents();
        this.controller = new DashboardController(this);
        setupSearchFieldBehavior();
    }
    
    public DashboardController getController() {
        return controller;
    }
    
    /**
     * Setup automatic placeholder clearing for search field
     */
    private void setupSearchFieldBehavior() {
        Search.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (Search.getText().equals(SEARCH_PLACEHOLDER)) {
                    Search.setText("");
                    Search.setForeground(java.awt.Color.BLACK);
                }
            }
            
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (Search.getText().trim().isEmpty()) {
                    Search.setText(SEARCH_PLACEHOLDER);
                    Search.setForeground(java.awt.Color.GRAY);
                }
            }
        });
        
        Search.setForeground(java.awt.Color.GRAY);
    }

    /**
     * UPDATE SESSION STATE
     */
    public void updateSessionState() {
        if (SessionManager.isLoggedIn()) {
            Profile.setToolTipText("My Profile");
        } else {
            Profile.setToolTipText("Login / Signup");
        }
        
        this.revalidate();
        this.repaint();
    }

    // ==================== PRODUCT DISPLAY METHODS ====================

    /**
     * ✅ FIXED: Creates a horizontal scrolling panel for product cards
     */
    public ProductCardPanel addProductCard(AdminProductModel product) {
        // Create grid panel on first call
        if (productGridPanel == null) {
            productGridPanel = new JPanel();
            productGridPanel.setLayout(new javax.swing.BoxLayout(productGridPanel, javax.swing.BoxLayout.X_AXIS));
            productGridPanel.setBackground(new java.awt.Color(0, 0, 0));
            
            // Clear and add to main container
            Productcontainer.removeAll();
            Productcontainer.add(productGridPanel, java.awt.BorderLayout.CENTER);
        }
        
        // Add card to grid panel
        ProductCardPanel card = new ProductCardPanel(product, null);
        productGridPanel.add(card);
        return card;
    }

    public void clearProductDisplay() {
        Productcontainer.removeAll();
        productGridPanel = null; // ✅ Reset grid panel
    }

    public void refreshProductDisplay() {
        Productcontainer.revalidate();
        Productcontainer.repaint();
    }

    public void resetSearchField() {
        Search.setText(SEARCH_PLACEHOLDER);
        Search.setForeground(java.awt.Color.GRAY);
    }
    
    /**
     * Get current search text (excluding placeholder)
     */
    public String getSearchText() {
        String text = Search.getText().trim();
        return text.equals(SEARCH_PLACEHOLDER) ? "" : text;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pop = new javax.swing.JPopupMenu();
        Account = new javax.swing.JMenuItem();
        Order = new javax.swing.JMenuItem();
        OUT = new javax.swing.JMenuItem();
        Header = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subname = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        Fav = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        Fav1 = new javax.swing.JButton();
        bannerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productcontainer = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        aboutus = new javax.swing.JLabel();
        aboutus1 = new javax.swing.JLabel();
        aboutus2 = new javax.swing.JLabel();
        aboutus3 = new javax.swing.JLabel();
        Help = new javax.swing.JButton();
        Contact = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        location = new javax.swing.JLabel();

        Pop.setBorder(null);
        Pop.setBorderPainted(false);
        Pop.setPreferredSize(new java.awt.Dimension(125, 125));

        Account.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account (2).png"))); // NOI18N
        Account.setText("My Account");
        Account.setBorder(null);
        Account.setBorderPainted(false);
        Account.addActionListener(this::AccountActionPerformed);
        Pop.add(Account);

        Order.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bag (2).png"))); // NOI18N
        Order.setText("Order Status");
        Order.setBorder(null);
        Order.setBorderPainted(false);
        Order.addActionListener(this::OrderActionPerformed);
        Pop.add(Order);

        OUT.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        OUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit (2).png"))); // NOI18N
        OUT.setText("Log Out");
        OUT.setBorder(null);
        OUT.setBorderPainted(false);
        OUT.addActionListener(this::OUTActionPerformed);
        Pop.add(OUT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 0, 0));

        name.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 30)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("GRAVE RUN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newlogo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        subname.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        subname.setForeground(new java.awt.Color(255, 255, 255));
        subname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subname.setText("RUN BEYOND THE GRAVE");

        Search.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Search.setText("Search by brands");
        Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFocusLost(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        search.setBorder(null);
        search.setBorderPainted(false);
        search.setFocusPainted(false);
        search.addActionListener(this::searchActionPerformed);

        Fav.setBackground(new java.awt.Color(0, 0, 0));
        Fav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fav.png"))); // NOI18N
        Fav.setBorder(null);
        Fav.setBorderPainted(false);
        Fav.setFocusPainted(false);
        Fav.addActionListener(this::FavActionPerformed);

        Profile.setBackground(new java.awt.Color(0, 0, 0));
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_a.png"))); // NOI18N
        Profile.setBorder(null);
        Profile.setBorderPainted(false);
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Profile.setFocusPainted(false);
        Profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Profile.addActionListener(this::ProfileActionPerformed);

        Fav1.setBackground(new java.awt.Color(0, 0, 0));
        Fav1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        Fav1.setBorder(null);
        Fav1.setBorderPainted(false);
        Fav1.setFocusPainted(false);
        Fav1.addActionListener(this::Fav1ActionPerformed);

        bannerPanel.setBackground(new java.awt.Color(60, 10, 10));
        bannerPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 182, 187));
        jLabel1.setText("NEW DROP • 2026 COLLECTION ");
        bannerPanel.add(jLabel1);
        jLabel1.setBounds(10, 0, 140, 20);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lil Nas X Blood Moon Edition");
        bannerPanel.add(jLabel3);
        jLabel3.setBounds(10, 20, 490, 50);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Crafted for the Fearless");
        bannerPanel.add(jLabel4);
        jLabel4.setBounds(540, 10, 300, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shoesbanner.jpg"))); // NOI18N
        bannerPanel.add(jLabel6);
        jLabel6.setBounds(350, 0, 170, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download_380x170.png"))); // NOI18N
        bannerPanel.add(jLabel5);
        jLabel5.setBounds(830, -10, 190, 110);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hell Can't Hold These Kicks");
        bannerPanel.add(jLabel7);
        jLabel7.setBounds(1040, 0, 340, 90);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner2.jpg"))); // NOI18N
        bannerPanel.add(jLabel8);
        jLabel8.setBounds(1390, 10, 130, 70);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(subname)))
                        .addGap(29, 29, 29)
                        .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(Fav1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Fav, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bannerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fav, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fav1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(name)
                                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Productcontainer.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(Productcontainer);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(0, 0, 0));

        aboutus.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setText("About Us");

        aboutus1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus1.setForeground(new java.awt.Color(255, 255, 255));
        aboutus1.setText("Where style meets comfort in every step.");

        aboutus2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus2.setForeground(new java.awt.Color(255, 255, 255));
        aboutus2.setText("Your go-to destination for everyday sneakers.");

        aboutus3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus3.setForeground(new java.awt.Color(255, 255, 255));
        aboutus3.setText("An online shoe store that makes browsing and buying footwear easy.");

        Help.setBackground(new java.awt.Color(20, 20, 20));
        Help.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        Help.setForeground(new java.awt.Color(255, 255, 255));
        Help.setText("Help");
        Help.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Help.setMargin(new java.awt.Insets(10, 20, 10, 20));
        Help.setMaximumSize(new java.awt.Dimension(180, 55));
        Help.setMinimumSize(new java.awt.Dimension(180, 55));
        Help.setPreferredSize(new java.awt.Dimension(180, 55));
        Help.addActionListener(this::HelpActionPerformed);

        Contact.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("Contact");

        mail.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("graverun16@gmail.com");

        phone.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("9808404997");

        location.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setText("Kathmandu, Nepal");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutus2)
                    .addComponent(aboutus3)
                    .addComponent(aboutus)
                    .addComponent(aboutus1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(location, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Contact, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(Contact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mail))
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(aboutus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aboutus1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(footerLayout.createSequentialGroup()
                                        .addComponent(aboutus2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aboutus3))
                                    .addGroup(footerLayout.createSequentialGroup()
                                        .addComponent(phone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(location)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
                               
  




    }//GEN-LAST:event_jLabel2MouseClicked

    private void SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusGained
       
    }//GEN-LAST:event_SearchFocusGained

    private void SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusLost
      
    }//GEN-LAST:event_SearchFocusLost

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
                                      
   


    }//GEN-LAST:event_searchActionPerformed

    private void FavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavActionPerformed
                                   
   

    }//GEN-LAST:event_FavActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed

    }//GEN-LAST:event_ProfileActionPerformed

    private void Fav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fav1ActionPerformed
   



   
    }//GEN-LAST:event_Fav1ActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
       
          // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
       
           // TODO add your handling code here:
    }//GEN-LAST:event_AccountActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
 
    
    }//GEN-LAST:event_OrderActionPerformed

    private void OUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OUTActionPerformed
       
        
    }//GEN-LAST:event_OUTActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Account;
    private javax.swing.JLabel Contact;
    private javax.swing.JButton Fav;
    private javax.swing.JButton Fav1;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Help;
    private javax.swing.JMenuItem OUT;
    private javax.swing.JMenuItem Order;
    private javax.swing.JPopupMenu Pop;
    private javax.swing.JPanel Productcontainer;
    private javax.swing.JButton Profile;
    private javax.swing.JTextField Search;
    private javax.swing.JLabel aboutus;
    private javax.swing.JLabel aboutus1;
    private javax.swing.JLabel aboutus2;
    private javax.swing.JLabel aboutus3;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel location;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JButton search;
    private javax.swing.JLabel subname;
    // End of variables declaration//GEN-END:variables

    public JButton getSearchButton() { return search; }
    public JTextField getSearchField() { return Search; }
    public JButton getFavoritesButton() { return Fav; }
    public JButton getCartButton() { return Fav1; }
    public JButton getProfileButton() { return Profile; }
    public JButton getHelpButton() { return Help; }
    public JLabel getLogoLabel() { return jLabel2; }
    public JPopupMenu getPopupMenu() { return Pop; }
    public JPanel getProductContainer() { return Productcontainer; }
    public JMenuItem getMenuItemAccount() { return Account; }
    public JMenuItem getMenuItemOrder() { return Order; }
    public JMenuItem getMenuItemLogout() { return OUT; }
}