/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author srsro
 */
public class dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form freeframe
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        motto1 = new javax.swing.JLabel();
        motto2 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        categories = new javax.swing.JButton();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        bannerPanel = new javax.swing.JPanel();
        Banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buynow = new javax.swing.JButton();
        bestSellers = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        productLabel1 = new javax.swing.JPanel();
        shoeImg = new javax.swing.JLabel();
        shoeName = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        buyNow2 = new javax.swing.JButton();
        favourite = new javax.swing.JButton();
        productlabel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buyNow1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        productlabel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buyNow3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        productlevel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        buynow4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        logo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 11, 11));
        getContentPane().setLayout(null);

        backgroundPanel.setBackground(new java.awt.Color(11, 11, 11));
        backgroundPanel.setLayout(null);

        motto1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        motto1.setForeground(new java.awt.Color(242, 242, 242));
        motto1.setText("GRAVE RUN ");
        motto1.setMaximumSize(new java.awt.Dimension(647, 629));
        motto1.setMinimumSize(new java.awt.Dimension(647, 629));
        backgroundPanel.add(motto1);
        motto1.setBounds(140, 30, 160, 20);

        motto2.setFont(new java.awt.Font("Constantia", 0, 10)); // NOI18N
        motto2.setForeground(new java.awt.Color(242, 242, 242));
        motto2.setText("RUN BEYOND THE GRAVE");
        backgroundPanel.add(motto2);
        motto2.setBounds(140, 40, 150, 30);

        searchPanel.setLayout(null);

        txtSearch.setText("Search sneakers, brands or collections… ");
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        searchPanel.add(txtSearch);
        txtSearch.setBounds(60, 0, 420, 35);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon_50x40.png"))); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        searchPanel.add(btnSearch);
        btnSearch.setBounds(0, 0, 60, 35);

        backgroundPanel.add(searchPanel);
        searchPanel.setBounds(300, 20, 480, 35);

        categories.setBackground(new java.awt.Color(0, 0, 0));
        categories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-15 153859.png"))); // NOI18N
        categories.setText("jButton1");
        categories.setBorder(null);
        backgroundPanel.add(categories);
        categories.setBounds(810, 10, 190, 50);

        login.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        login.setText("login");
        login.setBorderPainted(false);
        backgroundPanel.add(login);
        login.setBounds(1060, 20, 90, 30);

        signup.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        signup.setText("signup");
        backgroundPanel.add(signup);
        signup.setBounds(1170, 20, 90, 30);

        bannerPanel.setBackground(new java.awt.Color(60, 10, 10));
        bannerPanel.setLayout(null);

        Banner.setBackground(new java.awt.Color(60, 10, 10));
        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download_380x170.png"))); // NOI18N
        Banner.setText("jLabel1");
        bannerPanel.add(Banner);
        Banner.setBounds(530, 20, 380, 170);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 182, 187));
        jLabel1.setText("NEW DROP • 2025 COLLECTION ");
        bannerPanel.add(jLabel1);
        jLabel1.setBounds(20, 10, 140, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lil Nas X Blood Moon Edition");
        bannerPanel.add(jLabel2);
        jLabel2.setBounds(20, 40, 490, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crafted for the Fearless");
        bannerPanel.add(jLabel3);
        jLabel3.setBounds(100, 80, 300, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The GraveRun world: New ");
        bannerPanel.add(jLabel4);
        jLabel4.setBounds(30, 130, 230, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("items daily at 10 AM NPT");
        bannerPanel.add(jLabel5);
        jLabel5.setBounds(30, 160, 240, 20);

        buynow.setBackground(new java.awt.Color(0, 0, 0));
        buynow.setForeground(new java.awt.Color(255, 255, 255));
        buynow.setText("Buy Now");
        buynow.setBorderPainted(false);
        buynow.addActionListener(this::buynowActionPerformed);
        bannerPanel.add(buynow);
        buynow.setBounds(400, 160, 90, 30);

        backgroundPanel.add(bannerPanel);
        bannerPanel.setBounds(100, 110, 930, 210);

        bestSellers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bestSellers.setForeground(new java.awt.Color(255, 255, 255));
        bestSellers.setText("Best Sellers");
        backgroundPanel.add(bestSellers);
        bestSellers.setBounds(70, 340, 130, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(189, 189, 189));
        jLabel7.setText(" . . ");
        backgroundPanel.add(jLabel7);
        jLabel7.setBounds(520, 300, 150, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(".");
        backgroundPanel.add(jLabel8);
        jLabel8.setBounds(510, 300, 20, 40);

        jPanel2.setLayout(null);

        jButton7.setText("Help!");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel2.add(jButton7);
        jButton7.setBounds(10, 10, 170, 20);

        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 30, 140, 60);

        backgroundPanel.add(jPanel2);
        jPanel2.setBounds(0, 620, 1280, 100);

        productLabel1.setBackground(new java.awt.Color(73, 17, 17));
        productLabel1.setLayout(null);

        shoeImg.setText("jLabel1");
        productLabel1.add(shoeImg);
        shoeImg.setBounds(10, 20, 230, 87);

        shoeName.setForeground(new java.awt.Color(255, 250, 250));
        shoeName.setText("jLabel2");
        productLabel1.add(shoeName);
        shoeName.setBounds(10, 110, 38, 16);

        price.setForeground(new java.awt.Color(255, 250, 250));
        price.setText("jLabel3");
        productLabel1.add(price);
        price.setBounds(10, 130, 38, 16);

        buyNow2.setBackground(new java.awt.Color(29, 21, 21));
        buyNow2.setForeground(new java.awt.Color(255, 255, 255));
        buyNow2.setText("Buy now");
        productLabel1.add(buyNow2);
        buyNow2.setBounds(180, 120, 78, 17);

        favourite.setText("jButton2");
        favourite.addActionListener(this::favouriteActionPerformed);
        productLabel1.add(favourite);
        favourite.setBounds(250, 0, 21, 17);

        backgroundPanel.add(productLabel1);
        productLabel1.setBounds(340, 390, 265, 151);

        productlabel2.setBackground(new java.awt.Color(73, 17, 17));
        productlabel2.setLayout(null);

        jLabel6.setText("jLabel1");
        productlabel2.add(jLabel6);
        jLabel6.setBounds(10, 20, 230, 87);

        jLabel9.setForeground(new java.awt.Color(255, 250, 250));
        jLabel9.setText("jLabel2");
        productlabel2.add(jLabel9);
        jLabel9.setBounds(10, 110, 38, 16);

        jLabel10.setForeground(new java.awt.Color(255, 250, 250));
        jLabel10.setText("jLabel3");
        productlabel2.add(jLabel10);
        jLabel10.setBounds(10, 130, 38, 16);

        buyNow1.setBackground(new java.awt.Color(29, 21, 21));
        buyNow1.setForeground(new java.awt.Color(255, 255, 255));
        buyNow1.setText("Buy now");
        buyNow1.addActionListener(this::buyNow1ActionPerformed);
        productlabel2.add(buyNow1);
        buyNow1.setBounds(180, 120, 78, 17);

        jButton2.setText("jButton2");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        productlabel2.add(jButton2);
        jButton2.setBounds(250, 0, 21, 17);

        backgroundPanel.add(productlabel2);
        productlabel2.setBounds(20, 390, 265, 151);

        productlabel3.setBackground(new java.awt.Color(73, 17, 17));
        productlabel3.setLayout(null);

        jLabel11.setText("jLabel1");
        productlabel3.add(jLabel11);
        jLabel11.setBounds(10, 20, 230, 87);

        jLabel12.setForeground(new java.awt.Color(255, 250, 250));
        jLabel12.setText("jLabel2");
        productlabel3.add(jLabel12);
        jLabel12.setBounds(10, 110, 38, 16);

        jLabel13.setForeground(new java.awt.Color(255, 250, 250));
        jLabel13.setText("jLabel3");
        productlabel3.add(jLabel13);
        jLabel13.setBounds(10, 130, 38, 16);

        buyNow3.setBackground(new java.awt.Color(29, 21, 21));
        buyNow3.setForeground(new java.awt.Color(255, 255, 255));
        buyNow3.setText("Buy now");
        productlabel3.add(buyNow3);
        buyNow3.setBounds(180, 120, 78, 17);

        jButton4.setText("jButton2");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        productlabel3.add(jButton4);
        jButton4.setBounds(250, 0, 21, 17);

        backgroundPanel.add(productlabel3);
        productlabel3.setBounds(670, 390, 265, 151);

        productlevel4.setBackground(new java.awt.Color(73, 17, 17));
        productlevel4.setLayout(null);

        jLabel14.setText("jLabel1");
        productlevel4.add(jLabel14);
        jLabel14.setBounds(10, 20, 230, 87);

        jLabel15.setForeground(new java.awt.Color(255, 250, 250));
        jLabel15.setText("jLabel2");
        productlevel4.add(jLabel15);
        jLabel15.setBounds(10, 110, 38, 16);

        jLabel16.setForeground(new java.awt.Color(255, 250, 250));
        jLabel16.setText("jLabel3");
        productlevel4.add(jLabel16);
        jLabel16.setBounds(10, 130, 38, 16);

        buynow4.setBackground(new java.awt.Color(29, 21, 21));
        buynow4.setForeground(new java.awt.Color(255, 255, 255));
        buynow4.setText("Buy now");
        productlevel4.add(buynow4);
        buynow4.setBounds(180, 120, 78, 17);

        jButton6.setText("jButton2");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        productlevel4.add(jButton6);
        jButton6.setBounds(250, 0, 21, 17);

        backgroundPanel.add(productlevel4);
        productlevel4.setBounds(990, 390, 265, 151);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png_1_185x85.png"))); // NOI18N
        logo.setBorder(null);
        logo.setBorderPainted(false);
        backgroundPanel.add(logo);
        logo.setBounds(40, 10, 100, 80);

        getContentPane().add(backgroundPanel);
        backgroundPanel.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void buynowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buynowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buynowActionPerformed

    private void favouriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favouriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favouriteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void buyNow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyNow1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyNow1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JLabel bestSellers;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton buyNow1;
    private javax.swing.JButton buyNow2;
    private javax.swing.JButton buyNow3;
    private javax.swing.JButton buynow;
    private javax.swing.JButton buynow4;
    private javax.swing.JButton categories;
    private javax.swing.JButton favourite;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JButton logo;
    private javax.swing.JLabel motto1;
    private javax.swing.JLabel motto2;
    private javax.swing.JLabel price;
    private javax.swing.JPanel productLabel1;
    private javax.swing.JPanel productlabel2;
    private javax.swing.JPanel productlabel3;
    private javax.swing.JPanel productlevel4;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel shoeImg;
    private javax.swing.JLabel shoeName;
    private javax.swing.JButton signup;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables



}
