/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author srsro
 */
public class dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form freeframe
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        motto1 = new javax.swing.JLabel();
        motto2 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        categories = new javax.swing.JButton();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        bannerPanel = new javax.swing.JPanel();
        Banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buynow = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 11, 11));
        getContentPane().setLayout(null);

        backgroundPanel.setBackground(new java.awt.Color(11, 11, 11));
        backgroundPanel.setLayout(null);

        logo.setForeground(new java.awt.Color(242, 242, 242));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png_1_185x85.png"))); // NOI18N
        backgroundPanel.add(logo);
        logo.setBounds(0, -10, 130, 120);

        motto1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        motto1.setForeground(new java.awt.Color(242, 242, 242));
        motto1.setText("GRAVE RUN ");
        motto1.setMaximumSize(new java.awt.Dimension(647, 629));
        motto1.setMinimumSize(new java.awt.Dimension(647, 629));
        backgroundPanel.add(motto1);
        motto1.setBounds(140, 30, 160, 20);

        motto2.setFont(new java.awt.Font("Constantia", 0, 10)); // NOI18N
        motto2.setForeground(new java.awt.Color(242, 242, 242));
        motto2.setText("RUN BEYOND THE GRAVE");
        backgroundPanel.add(motto2);
        motto2.setBounds(140, 40, 150, 30);

        searchPanel.setLayout(null);

        txtSearch.setText("Search sneakers, brands or collections… ");
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        searchPanel.add(txtSearch);
        txtSearch.setBounds(60, 0, 420, 35);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon_50x40.png"))); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        searchPanel.add(btnSearch);
        btnSearch.setBounds(0, 0, 60, 35);

        backgroundPanel.add(searchPanel);
        searchPanel.setBounds(300, 20, 480, 35);

        categories.setBackground(new java.awt.Color(0, 0, 0));
        categories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-15 153859.png"))); // NOI18N
        categories.setText("jButton1");
        categories.setBorder(null);
        backgroundPanel.add(categories);
        categories.setBounds(810, 10, 190, 50);

        login.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        login.setText("login");
        login.setBorderPainted(false);
        backgroundPanel.add(login);
        login.setBounds(1050, 20, 90, 30);

        signup.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        signup.setText("signup");
        backgroundPanel.add(signup);
        signup.setBounds(1160, 20, 90, 30);

        bannerPanel.setBackground(new java.awt.Color(60, 10, 10));
        bannerPanel.setLayout(null);

        Banner.setBackground(new java.awt.Color(60, 10, 10));
        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download_380x170.png"))); // NOI18N
        Banner.setText("jLabel1");
        bannerPanel.add(Banner);
        Banner.setBounds(530, 20, 380, 170);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 182, 187));
        jLabel1.setText("NEW DROP • 2025 COLLECTION ");
        bannerPanel.add(jLabel1);
        jLabel1.setBounds(20, 10, 140, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lil Nas X Blood Moon Edition");
        bannerPanel.add(jLabel2);
        jLabel2.setBounds(20, 40, 490, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crafted for the Fearless");
        bannerPanel.add(jLabel3);
        jLabel3.setBounds(100, 80, 300, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The GraveRun world: New ");
        bannerPanel.add(jLabel4);
        jLabel4.setBounds(30, 130, 230, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("items daily at 10 AM NPT");
        bannerPanel.add(jLabel5);
        jLabel5.setBounds(30, 160, 240, 20);

        buynow.setBackground(new java.awt.Color(0, 0, 0));
        buynow.setForeground(new java.awt.Color(255, 255, 255));
        buynow.setText("Buy Now");
        buynow.setBorderPainted(false);
        buynow.addActionListener(this::buynowActionPerformed);
        bannerPanel.add(buynow);
        buynow.setBounds(400, 160, 90, 30);

        backgroundPanel.add(bannerPanel);
        bannerPanel.setBounds(100, 110, 930, 210);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Best Sellers");
        backgroundPanel.add(jLabel6);
        jLabel6.setBounds(70, 340, 130, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(189, 189, 189));
        jLabel7.setText(" . . ");
        backgroundPanel.add(jLabel7);
        jLabel7.setBounds(520, 300, 150, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(".");
        backgroundPanel.add(jLabel8);
        jLabel8.setBounds(510, 300, 20, 40);

        jPanel1.add(jLabel9);

        backgroundPanel.add(jPanel1);
        jPanel1.setBounds(60, 380, 265, 151);
        backgroundPanel.add(jPanel2);
        jPanel2.setBounds(0, 620, 1280, 100);

        getContentPane().add(backgroundPanel);
        backgroundPanel.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void buynowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buynowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buynowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton buynow;
    private javax.swing.JButton categories;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel motto1;
    private javax.swing.JLabel motto2;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton signup;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
