package view;

import controller.AdminOrderController;
import model.AdminOrderModel;
import javax.swing.*;
import java.awt.*;

/**
 * Dialog for changing order status
 */
public class EditOrderStatusDialog extends JDialog {
    
    private final AdminOrderController orderController;
    private final AdminOrderModel order;
    private boolean statusUpdated = false;
    
    public EditOrderStatusDialog(Frame parent, boolean modal, 
                                AdminOrderController orderController, AdminOrderModel order) {
        super(parent, "Change Order Status", modal);
        this.orderController = orderController;
        this.order = order;
        initComponents();
        loadOrderData();
        addActionListeners();
        setLocationRelativeTo(parent);
    }
    
    

private void loadOrderData() {
        orderIdLabel.setText("Order #" + order.getId());
        currentStatusLabel.setText(order.getStatus());
        
        // Set current status color
        setStatusColor(currentStatusLabel, order.getStatus());
        
        // Set the combo box to current status
        statusComboBox.setSelectedItem(order.getStatus());
    }

private void setStatusColor(JLabel label, String status) {
        switch (status.toLowerCase()) {
            case "pending":
                label.setForeground(new Color(255, 193, 7)); // Amber
                break;
            case "processing":
                label.setForeground(new Color(33, 150, 243)); // Blue
                break;
            case "shipped":
                label.setForeground(new Color(156, 39, 176)); // Purple
                break;
            case "delivered":
                label.setForeground(new Color(76, 175, 80)); // Green
                break;
            case "cancelled":
                label.setForeground(new Color(244, 67, 54)); // Red
                break;
            default:
                label.setForeground(new Color(200, 200, 200));
        }
    }
    
    private void addActionListeners() {
        saveButton.addActionListener(evt -> saveStatus());
        cancelButton.addActionListener(evt -> dispose());
    }
    
    private void saveStatus() {
        String newStatus = (String) statusComboBox.getSelectedItem();
        
        if (newStatus.equals(order.getStatus())) {
            JOptionPane.showMessageDialog(this,
                "No changes made to the order status.",
                "No Changes",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to change order status from '" + 
            order.getStatus() + "' to '" + newStatus + "'?",
            "Confirm Status Change",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = orderController.updateOrderStatus(order.getId(), newStatus);
            
            if (success) {
                JOptionPane.showMessageDialog(this,
                    "Order status updated successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                statusUpdated = true;
                dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Failed to update order status. Please try again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public boolean isStatusUpdated() {
        return statusUpdated;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        orderIdLabel = new javax.swing.JLabel();
        currentStatusLabelText = new javax.swing.JLabel();
        currentStatusLabel = new javax.swing.JLabel();
        newStatusLabelText = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Order Status");
        setBackground(new java.awt.Color(28, 28, 28));
        setMaximumSize(new java.awt.Dimension(500, 350));
        setMinimumSize(new java.awt.Dimension(500, 350));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(28, 28, 28));
        mainPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Change Order Status");
        mainPanel.add(titleLabel);
        titleLabel.setBounds(30, 20, 250, 30);

        separator1.setForeground(new java.awt.Color(60, 60, 60));
        mainPanel.add(separator1);
        separator1.setBounds(30, 60, 440, 10);

        orderIdLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        orderIdLabel.setForeground(new java.awt.Color(70, 30, 180));
        orderIdLabel.setText("Order #12345");
        mainPanel.add(orderIdLabel);
        orderIdLabel.setBounds(30, 85, 440, 25);

        currentStatusLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        currentStatusLabelText.setForeground(new java.awt.Color(255, 255, 255));
        currentStatusLabelText.setText("Current Status:");
        mainPanel.add(currentStatusLabelText);
        currentStatusLabelText.setBounds(40, 130, 140, 25);

        currentStatusLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        currentStatusLabel.setForeground(new java.awt.Color(255, 193, 7));
        currentStatusLabel.setText("pending");
        mainPanel.add(currentStatusLabel);
        currentStatusLabel.setBounds(190, 130, 270, 25);

        newStatusLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        newStatusLabelText.setForeground(new java.awt.Color(255, 255, 255));
        newStatusLabelText.setText("New Status:");
        mainPanel.add(newStatusLabelText);
        newStatusLabelText.setBounds(40, 180, 140, 25);

        statusComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pending", "processing", "shipped", "delivered", "cancelled" }));
        mainPanel.add(statusComboBox);
        statusComboBox.setBounds(190, 178, 270, 30);

        buttonPanel.setBackground(new java.awt.Color(28, 28, 28));

        saveButton.setBackground(new java.awt.Color(76, 175, 80));
        saveButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save Changes");
        saveButton.setFocusPainted(false);
        saveButton.setPreferredSize(new java.awt.Dimension(150, 40));
        buttonPanel.add(saveButton);

        cancelButton.setBackground(new java.awt.Color(108, 117, 125));
        cancelButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setFocusPainted(false);
        cancelButton.setPreferredSize(new java.awt.Dimension(120, 40));
        buttonPanel.add(cancelButton);

        mainPanel.add(buttonPanel);
        buttonPanel.setBounds(0, 260, 500, 60);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 500, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentStatusLabel;
    private javax.swing.JLabel currentStatusLabelText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel newStatusLabelText;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JSeparator separator1;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
