/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FavoriteDAO;
import javax.swing.JMenuItem;
import javax.swing.SwingUtilities;




/**
 *
 * @author Lenovo
 */
public class Favourites extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Favourites.class.getName());

    /**
     * Creates new form Dashboard
     */
    private FavoriteDAO favoriteDAO;

public Favourites(FavoriteDAO favoriteDAO) {
    this.favoriteDAO = favoriteDAO;
    initComponents();
    
}
public Favourites() {

    initComponents();
    
    Pop.add(Account);
    Pop.add(Order);
    Pop.add(OUT);


}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pop = new javax.swing.JPopupMenu();
        Account = new javax.swing.JMenuItem();
        Order = new javax.swing.JMenuItem();
        OUT = new javax.swing.JMenuItem();
        Header = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subname = new javax.swing.JLabel();
        Profile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productcontainer = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        aboutus = new javax.swing.JLabel();
        aboutus1 = new javax.swing.JLabel();
        aboutus2 = new javax.swing.JLabel();
        aboutus3 = new javax.swing.JLabel();
        Help = new javax.swing.JButton();
        Contact = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        location = new javax.swing.JLabel();

        Pop.setBorder(null);
        Pop.setBorderPainted(false);
        Pop.setPreferredSize(new java.awt.Dimension(125, 125));

        Account.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account (2).png"))); // NOI18N
        Account.setText("My Account");
        Account.setBorder(null);
        Account.setBorderPainted(false);
        Account.addActionListener(this::AccountActionPerformed);
        Pop.add(Account);

        Order.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bag (2).png"))); // NOI18N
        Order.setText("Order Status");
        Order.setBorder(null);
        Order.setBorderPainted(false);
        Pop.add(Order);

        OUT.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        OUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit (2).png"))); // NOI18N
        OUT.setText("Log Out");
        OUT.setBorder(null);
        OUT.setBorderPainted(false);
        Pop.add(OUT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 0, 0));

        name.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 30)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("GRAVE RUN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newlogo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        subname.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        subname.setForeground(new java.awt.Color(255, 255, 255));
        subname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subname.setText("RUN BEYOND THE GRAVE");

        Profile.setBackground(new java.awt.Color(0, 0, 0));
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_a.png"))); // NOI18N
        Profile.setBorder(null);
        Profile.setBorderPainted(false);
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Profile.setFocusPainted(false);
        Profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Profile.addActionListener(this::ProfileActionPerformed);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(subname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 737, Short.MAX_VALUE)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Productcontainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(Productcontainer);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(0, 0, 0));

        aboutus.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setText("About Us");

        aboutus1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus1.setForeground(new java.awt.Color(255, 255, 255));
        aboutus1.setText("Where style meets comfort in every step.");

        aboutus2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus2.setForeground(new java.awt.Color(255, 255, 255));
        aboutus2.setText("Your go-to destination for everyday sneakers.");

        aboutus3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        aboutus3.setForeground(new java.awt.Color(255, 255, 255));
        aboutus3.setText("An online shoe store that makes browsing and buying footwear easy.");

        Help.setBackground(new java.awt.Color(0, 0, 0));
        Help.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        Help.setForeground(new java.awt.Color(255, 255, 255));
        Help.setText("Help");
        Help.setBorder(null);
        Help.setBorderPainted(false);
        Help.setFocusPainted(false);
        Help.addActionListener(this::HelpActionPerformed);

        Contact.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("Contact");

        mail.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("graverun16@gmail.com");

        phone.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("9808404997");

        location.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setText("Kathmandu, Nepal");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutus)
                    .addComponent(aboutus1)
                    .addComponent(aboutus2)
                    .addComponent(aboutus3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contact, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mail)
                        .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(location, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addComponent(aboutus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutus2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutus3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                                .addComponent(Contact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(location)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
 Dashboard1 dashboard = new Dashboard1();
        dashboard.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel2MouseClicked

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed

    }//GEN-LAST:event_ProfileActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        HelpPage help=new HelpPage();
        help.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Account;
    private javax.swing.JLabel Contact;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Help;
    private javax.swing.JMenuItem OUT;
    private javax.swing.JMenuItem Order;
    private javax.swing.JPopupMenu Pop;
    private javax.swing.JPanel Productcontainer;
    private javax.swing.JButton Profile;
    private javax.swing.JLabel aboutus;
    private javax.swing.JLabel aboutus1;
    private javax.swing.JLabel aboutus2;
    private javax.swing.JLabel aboutus3;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel location;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel subname;
    // End of variables declaration//GEN-END:variables






public javax.swing.JButton getProfileButton() {
    return Profile;
}

public javax.swing.JPopupMenu getPopupMenu() {
    return Pop;
}

public javax.swing.JPanel getProductContainer() {
    return Productcontainer;
}

// Footer Help Button
public javax.swing.JButton getHelpButton() {
    return Help;
}
public javax.swing.JLabel getLogoLabel() {
    return jLabel2;
}
public JMenuItem getAccountMenu() {
    return Account;
}
public JMenuItem getOUTMenu() {
    return OUT;
}


public void addFavouritePanel(javax.swing.JPanel panel) {
    Productcontainer.add(panel);  
    Productcontainer.revalidate();
    Productcontainer.repaint();
}




    }







  



