/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SignupController;
import view.GraveRunLogin; 

/**
 *
 * @author Samsung
 */
public class GraveRunSignup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraveRunSignup.class.getName());

    /**
     * Creates new form GraveRunSignup
     */
    public GraveRunSignup() {
        initComponents();
        loginlink.setEditable(false); // non-editable
        loginlink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // hand cursor
        loginlink.setForeground(new java.awt.Color(204, 0, 0)); // red color for link-like feel
        loginlink.setBorder(null); // remove border if you want
        loginlink.setOpaque(false); // optional: blend with background

        loginlink.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        new GraveRunLogin().setVisible(true); // open login JFrame
        dispose(); // close current signup JFrame
    }

    @Override
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        loginlink.setForeground(new java.awt.Color(255, 0, 0)); // brighter red on hover
    }

    @Override
    public void mouseExited(java.awt.event.MouseEvent evt) {
        loginlink.setForeground(new java.awt.Color(204, 0, 0)); // original red
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupfront = new javax.swing.JPanel();
        Graverun = new javax.swing.JLabel();
        logan = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        confrimpassword = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        alreadyhaveanaccount = new javax.swing.JLabel();
        loginlink = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signupfront.setBackground(new java.awt.Color(0, 0, 0));

        Graverun.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        Graverun.setForeground(new java.awt.Color(204, 204, 204));
        Graverun.setText(" GRAVERUN");
        Graverun.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 0)));

        logan.setBackground(new java.awt.Color(0, 0, 0));
        logan.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        logan.setForeground(new java.awt.Color(255, 255, 255));
        logan.setText("RUN BEYOND THE GRAVE");

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Passsword");
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(this::passwordActionPerformed);

        confrimpassword.setBackground(new java.awt.Color(0, 0, 0));
        confrimpassword.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        confrimpassword.setForeground(new java.awt.Color(255, 255, 255));
        confrimpassword.setText("Confrim Password ");
        confrimpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        confrimpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confrimpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confrimpasswordFocusLost(evt);
            }
        });
        confrimpassword.addActionListener(this::confrimpasswordActionPerformed);

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(this::emailActionPerformed);

        Login.setBackground(new java.awt.Color(153, 0, 0));
        Login.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("CREATE ACCOUNT ");
        Login.addActionListener(this::LoginActionPerformed);

        alreadyhaveanaccount.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        alreadyhaveanaccount.setForeground(new java.awt.Color(255, 255, 255));
        alreadyhaveanaccount.setText("Already have an account?");

        loginlink.setBackground(new java.awt.Color(0, 0, 0));
        loginlink.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginlink.setForeground(new java.awt.Color(255, 255, 255));
        loginlink.setText("  LOGIN");
        loginlink.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));
        loginlink.addActionListener(this::loginlinkActionPerformed);

        javax.swing.GroupLayout signupfrontLayout = new javax.swing.GroupLayout(signupfront);
        signupfront.setLayout(signupfrontLayout);
        signupfrontLayout.setHorizontalGroup(
            signupfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupfrontLayout.createSequentialGroup()
                .addGroup(signupfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupfrontLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(Graverun))
                    .addGroup(signupfrontLayout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(logan))
                    .addGroup(signupfrontLayout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addGroup(signupfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signupfrontLayout.createSequentialGroup()
                                .addComponent(alreadyhaveanaccount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confrimpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signupfrontLayout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(Login)))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        signupfrontLayout.setVerticalGroup(
            signupfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupfrontLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Graverun, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logan)
                .addGap(96, 96, 96)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(confrimpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(signupfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alreadyhaveanaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginlink, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signupfront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signupfront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained

    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost

    }//GEN-LAST:event_passwordFocusLost

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void confrimpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confrimpasswordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_confrimpasswordFocusGained

    private void confrimpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confrimpasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_confrimpasswordFocusLost

    private void confrimpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrimpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confrimpasswordActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
 
    }//GEN-LAST:event_LoginActionPerformed

    private void loginlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginlinkActionPerformed
    new GraveRunLogin().setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_loginlinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraveRunSignup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Graverun;
    private javax.swing.JButton Login;
    private javax.swing.JLabel alreadyhaveanaccount;
    private javax.swing.JTextField confrimpassword;
    private javax.swing.JTextField email;
    private javax.swing.JLabel logan;
    private javax.swing.JTextField loginlink;
    private javax.swing.JTextField password;
    private javax.swing.JPanel signupfront;
    // End of variables declaration//GEN-END:variables
}
                                
