/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 11sah
 */
public class HelpPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HelpPage.class.getName());

    /**
     * Creates new form HelpPage
     */
    public HelpPage() {
    initComponents();
    this.setSize(1280, 720); // or your preferred size
    this.setLocationRelativeTo(null); // centers the window
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        orderstatus = new javax.swing.JPanel();
        topic1 = new javax.swing.JTextField();
        text1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        shippingpolicy = new javax.swing.JPanel();
        topic2 = new javax.swing.JTextField();
        text2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        returnpolicy = new javax.swing.JPanel();
        topic3 = new javax.swing.JTextField();
        text3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        topic = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        bg.setBackground(new java.awt.Color(44, 29, 29));

        orderstatus.setBackground(new java.awt.Color(255, 244, 239));
        orderstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        topic1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topic1.setText("    Order Status");
        topic1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        topic1.addActionListener(this::topic1ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(" \n\n   ✔ What the statuses mean\n    . Pending – We received your order.\n    . Processing – We’re preparing your items.\n    . Shipped – Your package is on the way.\n    . Out for Delivery – Courier will deliver today.\n    . Delivered – Order has reached you.\n\n\n   ✔ How to track an order\n     . Go to My Orders.\n     . Select the order you want to track.\n     . You will see the current status and tracking details.\n\n\n   ✔ If your order is delayed\n     . Delivery may be delayed due to weather or holidays.\n     . Contact support if it’s delayed more than 3 days from the expected date");
        jTextArea1.setBorder(null);
        text1.setViewportView(jTextArea1);

        javax.swing.GroupLayout orderstatusLayout = new javax.swing.GroupLayout(orderstatus);
        orderstatus.setLayout(orderstatusLayout);
        orderstatusLayout.setHorizontalGroup(
            orderstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderstatusLayout.createSequentialGroup()
                .addGroup(orderstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderstatusLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(topic1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orderstatusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        orderstatusLayout.setVerticalGroup(
            orderstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderstatusLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(topic1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        shippingpolicy.setBackground(new java.awt.Color(255, 244, 239));
        shippingpolicy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        topic2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topic2.setText("  Shipping Policy");
        topic2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        topic2.addActionListener(this::topic2ActionPerformed);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("  \n\n  ✔ Delivery Time\n    .  Standard delivery: 3–7 business days.\n    .  Express delivery: 1–3 business days (if available).\n\n\n  ✔ Shipping Charges\n    . Depends on commute time.\n\n\n  ✔ Shipping Areas\n    . We deliver to all major cities.\n    . Remote areas may take additional time.\n\n\n  ✔ Order Processing\n    . Orders are processed within 24–48 hours after payment.");
        jTextArea2.setBorder(null);
        text2.setViewportView(jTextArea2);

        javax.swing.GroupLayout shippingpolicyLayout = new javax.swing.GroupLayout(shippingpolicy);
        shippingpolicy.setLayout(shippingpolicyLayout);
        shippingpolicyLayout.setHorizontalGroup(
            shippingpolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingpolicyLayout.createSequentialGroup()
                .addGroup(shippingpolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shippingpolicyLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(topic2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shippingpolicyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        shippingpolicyLayout.setVerticalGroup(
            shippingpolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingpolicyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(topic2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        returnpolicy.setBackground(new java.awt.Color(255, 244, 239));
        returnpolicy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        topic3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topic3.setText(" Return/Refund Policy");
        topic3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        topic3.addActionListener(this::topic3ActionPerformed);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("  \n\n  ✔ Return Eligibility\n    . Items must be unused and in original packaging.\n    . Return request must be made within 7–14 days (your choice).\n\n  ✔ Items NOT eligible\n    . Used products\n\n  ✔ Return Process\n    . Go to My Orders\n    . Select Request Return\n    . Choose reason\n    \n  ✔ Refund Process\n    . Refund will be issued after we receive and inspect the item.\n    . Refund time: 3–7 business days to original payment method.");
        text3.setViewportView(jTextArea3);

        javax.swing.GroupLayout returnpolicyLayout = new javax.swing.GroupLayout(returnpolicy);
        returnpolicy.setLayout(returnpolicyLayout);
        returnpolicyLayout.setHorizontalGroup(
            returnpolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnpolicyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(topic3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(returnpolicyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        returnpolicyLayout.setVerticalGroup(
            returnpolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnpolicyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(topic3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        topic.setBackground(new java.awt.Color(44, 29, 29));
        topic.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("Need Some Help?");
        topic.setBorder(null);
        topic.addActionListener(this::topicActionPerformed);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(orderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shippingpolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnpolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(orderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(returnpolicy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shippingpolicy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(bg);
        bg.setBounds(0, 0, 1309, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicActionPerformed

    private void topic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topic1ActionPerformed

    private void topic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topic2ActionPerformed

    private void topic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topic3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HelpPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel orderstatus;
    private javax.swing.JPanel returnpolicy;
    private javax.swing.JPanel shippingpolicy;
    private javax.swing.JScrollPane text1;
    private javax.swing.JScrollPane text2;
    private javax.swing.JScrollPane text3;
    private javax.swing.JTextField topic;
    private javax.swing.JTextField topic1;
    private javax.swing.JTextField topic2;
    private javax.swing.JTextField topic3;
    // End of variables declaration//GEN-END:variables
}
