/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import javax.swing.ImageIcon;
import model.AdminProductModel;


/**
 *
 * @author Lenovo
 */
public class ProductCardPanel extends javax.swing.JPanel {
        private AdminProductModel product;
    private ProductSelectionListener listener;
        private int productId;
    
public ProductCardPanel(AdminProductModel product, ProductSelectionListener listener) {
    this.product = product;
    this.productId = product.getProductId();
    this.listener = listener;   // 🔥 THIS WAS MISSING
    initComponents();
    loadProductData();
}

    // Keep no-argument constructor for NetBeans GUI Builder
    public ProductCardPanel() {
        initComponents();
    }
private void handleClick() {
        if (listener != null) {
            listener.onProductSelected(productId);
        }
    }

    public interface ProductSelectionListener {
        void onProductSelected(int productId);
    }

    public void setProductSelectionListener(ProductSelectionListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productname = new javax.swing.JLabel();
        productimage = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(73, 17, 17));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(280, 380));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 380));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        productname.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        productname.setForeground(new java.awt.Color(255, 255, 255));
        productname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        productimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productimage.setPreferredSize(new java.awt.Dimension(260, 240));

        price.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productimage, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
 handleClick();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
handleClick();   // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered

    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited

    }//GEN-LAST:event_jPanel1MouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
handleClick();// TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
handleClick(); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed
                                  

public void setProductImage(String filename) {
    if (filename == null || filename.trim().isEmpty()) {
        productimage.setIcon(null);
        productimage.setText("No Image");
        return;
    }

    // CORRECT: Use "/images/" with leading slash, NO "src"
    java.net.URL imgURL = getClass().getResource("/images/" + filename.trim());

    if (imgURL != null) {
        ImageIcon icon = new ImageIcon(imgURL);
        java.awt.Image scaled = icon.getImage().getScaledInstance(180, 180, java.awt.Image.SCALE_SMOOTH);
        productimage.setIcon(new ImageIcon(scaled));
        productimage.setText(""); // Clear any text
    } else {
        productimage.setIcon(null);
        productimage.setText("Image Not Found");
        productimage.setForeground(java.awt.Color.RED);
        productimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        System.out.println("Resource not found: /images/" + filename.trim());
    }
}
public void setProductName(String name) {
    productname.setText(name);
}

public void setProductPrice(java.math.BigDecimal price) {
    if (price != null) {
        this.price.setText("Rs " + price.toPlainString());
    } else {
        this.price.setText("Rs 0");
    }
}





private void loadProductData() {
    if (product != null) {
        setProductName(product.getName()); // assuming ProductModel has getName()
        setProductPrice(product.getPrice()); // assuming ProductModel has getPrice()
        setProductImage(product.getImageUrl()); 
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel productimage;
    private javax.swing.JLabel productname;
    // End of variables declaration//GEN-END:variables


    public int getProductId() {
        return productId;
    }
}
