/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.DashboardController;
import java.awt.event.ActionListener;
/**
 *
 * @author srsro
 */
public class productFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(productFrame.class.getName());

    /**
     * Creates new form productFrame
     */
    public productFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productimage = new javax.swing.JLabel();
        productname = new javax.swing.JLabel();
        productprice = new javax.swing.JLabel();
        buynow = new javax.swing.JButton();
        favourites = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(73, 17, 17));
        jPanel1.setLayout(null);
        jPanel1.add(productimage);
        productimage.setBounds(10, 20, 230, 87);

        productname.setForeground(new java.awt.Color(255, 250, 250));
        productname.setText("jLabel2");
        jPanel1.add(productname);
        productname.setBounds(10, 110, 38, 16);

        productprice.setForeground(new java.awt.Color(255, 250, 250));
        productprice.setText("jLabel3");
        jPanel1.add(productprice);
        productprice.setBounds(10, 130, 38, 16);

        buynow.setBackground(new java.awt.Color(29, 21, 21));
        buynow.setForeground(new java.awt.Color(255, 255, 255));
        buynow.setText("Buy now");
        jPanel1.add(buynow);
        buynow.setBounds(180, 120, 78, 17);

        favourites.setBackground(new java.awt.Color(73, 17, 17));
        favourites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fav.png"))); // NOI18N
        favourites.setBorder(null);
        favourites.addActionListener(this::favouritesActionPerformed);
        jPanel1.add(favourites);
        favourites.setBounds(230, 0, 40, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 265, 151);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void favouritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favouritesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favouritesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new productFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buynow;
    private javax.swing.JButton favourites;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productimage;
    private javax.swing.JLabel productname;
    private javax.swing.JLabel productprice;
    // End of variables declaration//GEN-END:variables
public void BuynowListner(ActionListener listner){
    buynow.addActionListener(listner);  
}
public void FavouriteListner(ActionListener listner){
    favourites.addActionListener(listner);
}
public javax.swing.JLabel getProductimage(){
    return productimage;
}
public javax.swing.JLabel getProductname(){
    return productname;
}
public javax.swing.JLabel getProductprice(){
    return productprice;
}
}