/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
/**
 *
 * @author Lenovo
 */
public class ProductCartPanel extends javax.swing.JPanel {
private int productId;
    private BigDecimal unitPrice = BigDecimal.ZERO;
    private int quantity = 1;
    /**
     * Creates new form ProductCardPnel
     */
    public ProductCartPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productimage = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Quantity = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        productname = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(73, 17, 17));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(280, 380));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 380));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        productimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productimage.setPreferredSize(new java.awt.Dimension(260, 240));

        price.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N

        Quantity.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Quantity.setOpaque(true);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(this::jButton9ActionPerformed);

        Total.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total.setOpaque(true);

        productname.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        productname.setForeground(new java.awt.Color(255, 255, 255));
        productname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productimage, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                    .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(productname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(productimage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


public void setProductImage(String filename) {
    java.net.URL imgURL = getClass().getResource("/images/" + filename);
    if (imgURL != null) {
        ImageIcon icon = new ImageIcon(imgURL);
        java.awt.Image scaled = icon.getImage().getScaledInstance(180, 180, java.awt.Image.SCALE_SMOOTH);
        productimage.setIcon(new ImageIcon(scaled));
        productimage.setText(""); 
    } else {
        productimage.setIcon(null);
        productimage.setText("Image Not Found");
        productimage.setForeground(java.awt.Color.RED);
        productimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        System.out.println("❌ Image not found: /images/" + filename);
    }
}



public void setProductName(String name) {
    productname.setText(name);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel Total;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel productimage;
    private javax.swing.JLabel productname;
    // End of variables declaration//GEN-END:variables


    public void setProductId(int productId) {
        this.productId = productId;
    }
private void updateTotal() {
    BigDecimal total = unitPrice.multiply(BigDecimal.valueOf(quantity));
    Total.setText("Rs " + total.toPlainString());
}
public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
        price.setText("Rs " + unitPrice.toPlainString());
        updateTotal();
    }

public void setQuantity(int qty) {
        if (qty >= 1) {
            this.quantity = qty;
            Quantity.setText(String.valueOf(qty));
            updateTotal();
        }
    }

    public int getQuantity() {
        return quantity;
    }

    public int getProductId() {
        return productId;
    }

   


public void addQuantityListeners(Runnable onQuantityChange) {
    jButton5.addActionListener(e -> {
        setQuantity(quantity + 1);
        if (onQuantityChange != null) onQuantityChange.run();
    });
    jButton6.addActionListener(e -> {
        if (quantity > 1) {
            setQuantity(quantity - 1);
            if (onQuantityChange != null) onQuantityChange.run();
        }
    });
}

public void addDeleteListener(Runnable onDelete) {
    jButton9.addActionListener(e -> {
        if (onDelete != null) onDelete.run();
    });
}

public BigDecimal getTotalPrice() {
    return unitPrice.multiply(BigDecimal.valueOf(quantity));
}
}



