/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import model.AdminProductModel;
import dao.CartDAO;
import dao.FavoriteDAO;
/**
 *
 * @author Lenovo
 */
public class ProductDetail extends javax.swing.JPanel {
private int productId;
 private final AdminProductModel product;

 

    /**
     * Creates new form ProductCardPnel
     * @param product
     */
public ProductDetail(AdminProductModel product) {
    this.product = product;
    initComponents();
    loadProductData();
    loadSizes();
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productimage = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        productname1 = new javax.swing.JLabel();
        Sizecombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Adfav = new javax.swing.JButton();
        Adcart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));
        setPreferredSize(new java.awt.Dimension(1280, 550));

        jPanel1.setBackground(new java.awt.Color(73, 17, 17));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 500));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productimage.setPreferredSize(new java.awt.Dimension(260, 240));
        jPanel1.add(productimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 500, 400));

        Price.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 300, 50));

        productname1.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        productname1.setForeground(new java.awt.Color(255, 255, 255));
        productname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(productname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1180, 60));

        Sizecombo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Sizecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US 7/EU 40", "US 8/EU 41", "US 9/EU 42.5", "US 10/EU 44", "US 11/EU 45", " ", " " }));
        Sizecombo.setSelectedIndex(-1);
        Sizecombo.addActionListener(this::SizecomboActionPerformed);
        jPanel1.add(Sizecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 250, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buy Now");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(106, 14, 14), 5, true));
        jButton1.setFocusPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(350, 65));
        jButton1.setMinimumSize(new java.awt.Dimension(350, 65));
        jButton1.setPreferredSize(new java.awt.Dimension(350, 65));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 250, 60));

        Adfav.setBackground(new java.awt.Color(106, 14, 14));
        Adfav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fav.png"))); // NOI18N
        Adfav.setBorder(null);
        Adfav.setBorderPainted(false);
        Adfav.setContentAreaFilled(false);
        Adfav.setFocusPainted(false);
        Adfav.addActionListener(this::AdfavActionPerformed);
        jPanel1.add(Adfav, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 50, 50));

        Adcart.setBackground(new java.awt.Color(0, 0, 0));
        Adcart.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Adcart.setForeground(new java.awt.Color(255, 255, 255));
        Adcart.setText("Add to Cart");
        Adcart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(106, 14, 14), 3, true));
        Adcart.setFocusPainted(false);
        Adcart.addActionListener(this::AdcartActionPerformed);
        jPanel1.add(Adcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 250, 60));

        description.setEditable(false);
        description.setBackground(new java.awt.Color(73, 17, 17));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setLineWrap(true);
        description.setRows(5);
        description.setWrapStyleWord(true);
        description.setBorder(null);
        jScrollPane1.setViewportView(description);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 640, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void AdcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdcartActionPerformed

    }//GEN-LAST:event_AdcartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed



    }//GEN-LAST:event_jButton1ActionPerformed
    // TODO add your handling code here:

    private void SizecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizecomboActionPerformed

    private void AdfavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdfavActionPerformed

    }//GEN-LAST:event_AdfavActionPerformed


public void setProductImage(String filename) {
    java.net.URL imgURL = getClass().getResource("/images/" + filename);
    if (imgURL != null) {
        ImageIcon icon = new ImageIcon(imgURL);
        java.awt.Image scaled = icon.getImage().getScaledInstance(180, 180, java.awt.Image.SCALE_SMOOTH);
        productimage.setIcon(new ImageIcon(scaled));
        productimage.setText(""); 
    } else {
        productimage.setIcon(null);
        productimage.setText("Image Not Found");
        productimage.setForeground(java.awt.Color.RED);
        productimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        System.out.println("❌ Image not found: /images/" + filename);
    }
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adcart;
    private javax.swing.JButton Adfav;
    private javax.swing.JLabel Price;
    private javax.swing.JComboBox<String> Sizecombo;
    private javax.swing.JTextArea description;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel productimage;
    private javax.swing.JLabel productname1;
    // End of variables declaration//GEN-END:variables


    public void setProductId(int productId) {
        this.productId = productId;
    }

private void loadProductData() {
    if (this.product == null) return;

    productname1.setText(product.getName());
    Price.setText(product.getFormattedPrice());
    
    // ✅ ADD THIS: Load description
    if (product.getDescription() != null && !product.getDescription().trim().isEmpty()) {
        description.setText(product.getDescription());
    } else {
        description.setText("No description available.");
    }
    
    // ✅ ADD THIS: Load product image
    if (product.getImageUrl() != null && !product.getImageUrl().trim().isEmpty()) {
        setProductImage(product.getImageUrl());
    }
    
    Sizecombo.setSelectedItem(product.getSize());
}





    public int getProductId() {
        return productId;
    }
    public javax.swing.JButton getAddToCartButton() {
    return Adcart;
}

public javax.swing.JButton getBuyNowButton() {
    return jButton1;
}

public javax.swing.JButton getFavoriteButton() {
    return Adfav;
}

public String getSelectedSize() {
    Object selected = Sizecombo.getSelectedItem();
    return selected != null ? selected.toString().trim() : null;
// Public getters for controller
}
public javax.swing.JLabel getProductNameLabel() {
    return productname1;
}

public javax.swing.JLabel getPriceLabel() {
    return Price;
}

public javax.swing.JTextArea getDescriptionLabel() {
    return description;
}

public javax.swing.JLabel getProductImageLabel() {
    return productimage;
}

public javax.swing.JComboBox<String> getSizeComboBox() {
    return Sizecombo;
}

public void setProductName(String name) {
    productname1.setText(name != null ? name : "Product Name");
}

public void setProductPrice(java.math.BigDecimal price) {
    Price.setText(price != null ? "Rs " + price.toPlainString() : "Rs 0");
}

public void setDescription(String desc) {
    description.setText(desc != null ? desc : "No description available.");
}

private void loadSizes() {
    Sizecombo.removeAllItems();

    Sizecombo.addItem("Select Size");
    Sizecombo.addItem("US 7/EU 40");
    Sizecombo.addItem("US 8/EU 41");
    Sizecombo.addItem("US 9/EU 42.5");
    Sizecombo.addItem("US 10/EU 44");
    Sizecombo.addItem("US 11/EU 45");
}

}











