package view;

import model.AdminProductModel;
import javax.swing.*;
import java.awt.*;

/**
 * Dialog to display detailed product information
 */
public class ProductDetailsDialog extends JDialog {
    
    private AdminProductModel product;
    
   
    
    public ProductDetailsDialog(Frame parent, AdminProductModel product) {
        super(parent, "Product Details", true);
        this.product = product;
        initComponents();
        loadProductData();
        setLocationRelativeTo(parent);
        
        // Add close button action
        closeButton.addActionListener(e -> dispose());
    }
    
    private void loadProductData() {
        if (product != null) {
            productIdLabel.setText(String.valueOf(product.getProductId()));
            productNameLabel.setText(product.getName());
            categoryLabel.setText(product.getCategory());
            priceLabel.setText("Rs " + String.format("%.2f", product.getPrice()));
            stockLabel.setText(String.valueOf(product.getStockQuantity()) + " units");
            descriptionArea.setText(product.getDescription() != null ? product.getDescription() : "No description available");
        }
    }

  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        idLabelText = new javax.swing.JLabel();
        nameLabelText = new javax.swing.JLabel();
        categoryLabelText = new javax.swing.JLabel();
        priceLabelText = new javax.swing.JLabel();
        stockLabelText = new javax.swing.JLabel();
        productIdLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        descriptionLabelText = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Details");
        setBackground(new java.awt.Color(28, 28, 28));
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(28, 28, 28));
        mainPanel.setMaximumSize(new java.awt.Dimension(550, 500));
        mainPanel.setMinimumSize(new java.awt.Dimension(550, 500));
        mainPanel.setPreferredSize(new java.awt.Dimension(550, 500));
        mainPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Product Details");
        mainPanel.add(titleLabel);
        titleLabel.setBounds(30, 20, 220, 35);

        separator1.setForeground(new java.awt.Color(60, 60, 60));
        mainPanel.add(separator1);
        separator1.setBounds(30, 65, 490, 3);

        idLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        idLabelText.setForeground(new java.awt.Color(255, 255, 255));
        idLabelText.setText("Product ID:");
        mainPanel.add(idLabelText);
        idLabelText.setBounds(40, 85, 130, 25);

        nameLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        nameLabelText.setForeground(new java.awt.Color(255, 255, 255));
        nameLabelText.setText("Product Name:");
        mainPanel.add(nameLabelText);
        nameLabelText.setBounds(40, 125, 130, 25);

        categoryLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        categoryLabelText.setForeground(new java.awt.Color(255, 255, 255));
        categoryLabelText.setText("Category:");
        mainPanel.add(categoryLabelText);
        categoryLabelText.setBounds(40, 165, 130, 25);

        priceLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        priceLabelText.setForeground(new java.awt.Color(255, 255, 255));
        priceLabelText.setText("Price:");
        mainPanel.add(priceLabelText);
        priceLabelText.setBounds(40, 205, 130, 25);

        stockLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        stockLabelText.setForeground(new java.awt.Color(255, 255, 255));
        stockLabelText.setText("Stock Quantity:");
        mainPanel.add(stockLabelText);
        stockLabelText.setBounds(40, 245, 130, 25);

        productIdLabel.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        productIdLabel.setForeground(new java.awt.Color(200, 200, 200));
        mainPanel.add(productIdLabel);
        productIdLabel.setBounds(180, 85, 330, 25);

        productNameLabel.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        productNameLabel.setForeground(new java.awt.Color(200, 200, 200));
        mainPanel.add(productNameLabel);
        productNameLabel.setBounds(180, 125, 330, 25);

        categoryLabel.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(200, 200, 200));
        mainPanel.add(categoryLabel);
        categoryLabel.setBounds(180, 165, 330, 25);

        priceLabel.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(76, 175, 80));
        mainPanel.add(priceLabel);
        priceLabel.setBounds(180, 205, 330, 25);

        stockLabel.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        stockLabel.setForeground(new java.awt.Color(200, 200, 200));
        mainPanel.add(stockLabel);
        stockLabel.setBounds(180, 245, 330, 25);

        separator2.setForeground(new java.awt.Color(60, 60, 60));
        mainPanel.add(separator2);
        separator2.setBounds(30, 285, 490, 2);

        descriptionLabelText.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        descriptionLabelText.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabelText.setText("Description:");
        mainPanel.add(descriptionLabelText);
        descriptionLabelText.setBounds(40, 300, 130, 25);

        scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));

        descriptionArea.setEditable(false);
        descriptionArea.setBackground(new java.awt.Color(43, 43, 43));
        descriptionArea.setColumns(20);
        descriptionArea.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        descriptionArea.setForeground(new java.awt.Color(200, 200, 200));
        descriptionArea.setLineWrap(true);
        descriptionArea.setRows(5);
        descriptionArea.setWrapStyleWord(true);
        descriptionArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        scrollPane.setViewportView(descriptionArea);

        mainPanel.add(scrollPane);
        scrollPane.setBounds(40, 330, 470, 90);

        closeButton.setBackground(new java.awt.Color(70, 130, 180));
        closeButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Close");
        closeButton.setFocusPainted(false);
        mainPanel.add(closeButton);
        closeButton.setBounds(215, 435, 120, 40);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 550, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryLabelText;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JLabel descriptionLabelText;
    private javax.swing.JLabel idLabelText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabelText;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabelText;
    private javax.swing.JLabel productIdLabel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel stockLabelText;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}